[package]
name = "sql-split-reader"
version = {workspace=true}
edition = {workspace=true}
authors = {workspace=true}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "reader_bench"
harness = false
path = "src/benches/reader_bench.rs"
