[package]
name = "sql-split-cli"
version = {workspace=true}
edition = {workspace=true}
authors = {workspace=true}

[dependencies]
sql-split-reader={workspace=true}
clap={version="2", features=["yaml"]}
flamegraph = "0.6.2"

[profile.release]
debug = true

